const verbs = [
  'to eat : comer',
  'to drink : beber',
  'to have : tener',
  'to want/love : querer',
  'to open : abrir',
  'to die : morir',
  'to live : vivir',
  'to swim : nadar',
  'to know : saber',
  'to write : escriber',
  'to read : leer',
  'to understand : comprender',
  'to ask : preguntar',
  'to listen : escuchar',
  'to see : ver',
  'to hear : oír',
  'to do/make : hacer',
  'to go : ir',
  'to arrive : llegar',
  'to follow : seguir',
  'to give : dar',
  'to speak : hablar',
  'to find : encontrar',
  'to believe : creer',
  'to leave : salir',
  'to come : venir',
  'to watch : mirar',
  'to start/begin : empezar',
  'to work : trabajar',
  'to need : necesitar',
  'to create : crear',
  'to study : estudiar',
  'to pay : pagar',
  'to help : ayudar',
  'to run : correr',
  'to touch/play : tocar',
  'to return : volver',
  'to hope/wait : esperar',
  'to search for : buscar',
  'to lose : perder',
  'to remember : recordar',
  'to take : tomar',
];

const colors = [
  'black : negro',
  'white : blanco',
  'blue : azul',
  'red : rojo',
  'green : verde',
  'yellow : amarillo',
  'pink : rosa',
  'grey : gris',
  'brown : marrón',
  'purple : morado',
  'orange : naranja',
  'light : claro',
  'dark : oscuro',
];

const animals = [
  'dog : perro',
  'cat : gato',
  'cow : vaca',
  'horse : caballo',
  'elephant : elefante',
  'pig : cerdo',
  'turtle : tortuga',
  'snake : serpiente',
  'donkey : burro',
  'lion : león',
  'monkey : mono',
  'tiger : tigre',
  'wolf : lobo',
  'bear : oso',
  'crab : cangrejo',
  'rabbit : conejo',
  'penguin : pingüino',
  'mouse : ratón',
  'fox : zorro',
  'bull : toro',
  'fish : pez',
];

const emotions = [
  'happy : feliz',
  'sad : triste',
  'tired : cansado',
  'worried : preocupado',
  'surprised : sorprendido',
  'excited : emocionado',
  'shy : tímido',
  'angry : enfadado',
  'confused : confundido',
  'nervous : nervioso',
  'bored : aburrido',
  'comfortable : cómodo',
  'busy : ocupado',
  'in love : enamorado',
  'furious : furioso',
];
